# Generated by Django 5.0.4 on 2024-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sleep_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepwalkingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("intensity", models.CharField(max_length=255)),
            ],
        ),
    ]
