# Generated by Django 5.0.4 on 2024-05-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rug',
            old_name='status',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='dominant_color',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='length',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='material',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='stock_number',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='type',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='width',
        ),
        migrations.AddField(
            model_name='rug',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rug',
            name='country_of_origin',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='rug',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rug',
            name='size',
            field=models.CharField(default='Unknown Size', max_length=50),
        ),
        migrations.AddField(
            model_name='rug',
            name='sku',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rug',
            name='style',
            field=models.CharField(choices=[('Oushak', 'Oushak'), ('Modern', 'Modern'), ('Afshar', 'Afshar')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rug',
            name='age',
            field=models.CharField(choices=[('Antique', 'Antique'), ('Antique Reproduction', 'Antique Reproduction'), ('New', 'New')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rug',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rug',
            name='texture',
            field=models.CharField(choices=[('Flatweave', 'Flatweave'), ('High-low', 'High-low'), ('Hooked', 'Hooked'), ('Pile', 'Pile')], max_length=50),
        ),
    ]
