# Generated by Django 5.0.4 on 2024-05-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_status_rug_color_remove_rug_dominant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rug',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rug_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.rug')),
            ],
        ),
    ]
